{% set name = "bqplot-image-gl" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bc010fb14f0b25cdd74ecd982b2885523da4d7694258ed9355f2ed4bc22a82ed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - jupyterlab >=3.6
  run:
    - python >=3.7
    - ipywidgets >=7.0.0
    - bqplot >=0.12
    - pillow

test:
  imports:
    - bqplot_image_gl

about:
  home: http://github.com/glue-viz/bqplot-image-gl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widget for displaying images with WebGL in bqplot
  dev_url: https://github.com/glue-viz/bqplot-image-gl

extra:
  recipe-maintainers:
    - astrofrog
    - maartenbreddels
    - mwcraig
