{% set name = "bqplot-image-gl" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 536326c56a15e2aa30cf257b838a7003d7d4310ed0b8b42650a3e85a4b631925

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ipywidgets >=7.0.0
    - bqplot >=0.12

test:
  imports:
    - bqplot_image_gl

about:
  home: http://github.com/glue-viz/bqplot-image-gl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widget for displaying images with WebGL in bqplot
  dev_url: https://github.com/glue-viz/bqplot-image-gl

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - maartenbreddels
