{% set name = "bqplot-image-gl" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 158e3b14f028a430c53b7ea9883adc6fd6867d10e7820b1a8560f1fe07a0c54f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - bqplot >=0.12

test:
  imports:
    - bqplot_image_gl

about:
  home: http://github.com/glue-viz/bqplot-image-gl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widget for displaying images with WebGL in bqplot
  dev_url: https://github.com/glue-viz/bqplot-image-gl

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - maartenbreddels
