{% set name = "bqplot-image-gl" %}
{% set version = "1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b744d79d29d1ad62fcf1b020200ef09ae22db087287f07fa899f99c763281e3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging >=0.7
    - jupyterlab >=3
  run:
    - python >=3.6
    - ipywidgets >=7.0.0
    - bqplot >=0.12

test:
  imports:
    - bqplot_image_gl

about:
  home: http://github.com/glue-viz/bqplot-image-gl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widget for displaying images with WebGL in bqplot
  dev_url: https://github.com/glue-viz/bqplot-image-gl

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - maartenbreddels
    - mwcraig
