{% set name = "bqplot-image-gl" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d3fa7225dcae800bd7b1db483100185260838783d6b37648edda2d147a254194

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-jupyter-builder
    - jupyterlab >=3.6
  run:
    - python >={{ python_min }}
    - ipywidgets >=7.0.0
    - bqplot >=0.12
    - pillow

test:
  imports:
    - bqplot_image_gl
  requires:
    - python {{ python_min }}

about:
  home: http://github.com/glue-viz/bqplot-image-gl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter widget for displaying images with WebGL in bqplot
  dev_url: https://github.com/glue-viz/bqplot-image-gl

extra:
  recipe-maintainers:
    - astrofrog
    - maartenbreddels
    - mwcraig
